#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyDiaryApp.Resource", IsApplication=true)]

namespace MyDiaryApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorBack = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_launcher_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int bottom_bg = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int header_bg = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int next = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F030000
			public const int robot = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int roboto_bold = 2130903041;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int btn = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int btnLogin = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int btnRegister = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int dateEntry = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int etConfirm = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int etDetails = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int etPassword = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int etSubject = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int etUserName = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int fstTxt = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int listEntries = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int lnkLogin = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int lnkRegister = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int loginscrn = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int menuHome = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int menuLogOut = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int radioAdd = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int radioDelete = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int radioGroup = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int radioView = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int secTxt = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int spinnerSubject = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int textDate = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int textDetails = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int textSubject = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int thirdTxt = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int tv1 = 2130968602;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_add = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int activity_delete = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int activity_home = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int activity_intro = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int activity_main = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int activity_register = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int activity_view = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int list_row = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int spinner_row = 2131034120;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int mainmenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
